### ISSUE TITLE
gazette expects the config file to be called `gazette.yaml`

### ISSUE THREAD

**Issue by booyaa** [Stebalien/gazetta#12]
The [bootstrap](https://github.com/Stebalien/gazetta-bootstrap) repo has called it `config.yaml`.

Do you want me to PR the bootstrap repo and rename the file? Or does it need to be fixed in the [gazette-bin](https://github.com/Stebalien/gazetta-bin) repo?

**Comment by Stebalien** [comment]
Oops... The bootstrap repo is incorrect, it should be `gazetta.yaml`. Thanks for catching that!

**Comment by Stebalien** [comment]
Note: It's gazett**a**, not gazett**e**. It's nadslang (from A Clockwork Orange).
